[package]

name = "httpd"
version = "0.0.1"
authors = ["justin"]

[dependencies.flate2]
git = "https://github.com/alexcrichton/flate2-rs"

[dependencies.conduit-mime-types]
git = "https://github.com/conduit-rust/mime-types"
